### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by FergusFettes** [demoskp/flask-query-builder#1]
I couldn't think of a good way to do this but I wanted to do a pr-style review of some parts so I'm doing it here.

In `flask_query_builder/filters.py`, this function:
```
class PartialFilter(Filter):
    """Perform a case-insensitive wildcard filter on a model field"""
    def filter(self, query, model, filter_name, values):
        if len(values) == 1:
            return query.filter(getattr(model, filter_name).ilike(f"%{values[0]}%"))
        else:
            q = query
            for value in values:
                q = q.filter(getattr(model, filter_name).ilike(f"%{value}%"))
            return q
```
can be simplified to
```
class PartialFilter(Filter):
    """Perform a case-insensitive wildcard filter on a model field"""
    def filter(self, query, model, filter_name, values):
        for value in values:
            query = query.filter(getattr(model, filter_name).ilike(f"%{value}%"))
        return query
```
surely?

There doesn't seem to be a single test that uses the 
```
    QueryBuilder(model=User, query=query) // start from an existing query
```
syntax of using another query (also that is a javascript comment ;P ).

I think there needs to be more documentation/examples. Looking through the code, if I didn't have access to examples I would struggle to understand how it works. 

However that might just be my inexperience in dealing with flask applications talking ;).

Am I right in thinking that this function is where the magic actually happens (and the corresponding one for filters):
```
    def _get_applied_sorts(self) -> List[AppliedSort]:
        """Get the list of sorts applied on the request"""
        raw_sorts = request.args.get("sort")
        if raw_sorts is None:
            return []

        raw_sorts = raw_sorts.split(",")
        formatted_sorts = []
        for sort in raw_sorts:
            if sort[0] == "-":
                final_sort = AppliedSort(sort[1:], True)
            else:
                final_sort = AppliedSort(sort)

            formatted_sorts.append(final_sort)

        return formatted_sorts
```
and that when the query is finally being built as a request is coming in, this is the function that compares the set of sorts that the request is trying to apply to the set of sorts that are allowed?

If so I would draw more attention to it, or just write something along the lines of what I just wrote in the docs. Maybe anyone using this library would understand this easily, but I think it would also be fine to spell it out.

Overall, looks like a pretty nifty piece of work! Congrats!

**Comment by demoskp** [comment]
On the first point you are right the first part of the code is redundant but I wouldn't bother making a PR just for that however since you suggested more tests on your second point I would happily accept a PR that includes both of those changes.

The method you pointed gets the sorts from the request object its in another function that an exception is thrown if one of these requested sort or filters is not in the allowed list.

The repo has a limited set of example however there is a link to a comprehensive examples guide on https://petsas.dev/projects/flask-query-builder

For the specific one you mentioned https://petsas.dev/projects/flask-query-builder#works-together-nicely-with-existing-queries

Feel free to make a PR with your suggested changes and I will happily review it.
